service: static-content-challenge 
provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: eu-west-2 
  memorySize: 128
functions:
  app:
    handler: src/lambda.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true